services:
  drone-vc-m:
    build: .
    environment:
      API_ID: $API_ID  
      API_HASH: $API_HASH  
      BOT_TOKEN: $BOT_TOKEN 
      OWNER_ID: $OWNER_ID
      SUDO_USERS: $SUDO_USERS
    resources:
      cpu: 1000m
      memory: 3Gi
